### 6388040
###  Week 6 : The use of Python Library (SciPy)

Exercise 1) Now, try to create the final scores of 20 students in Jupyter
Notebook as follows:

In [13]:
import scipy
from scipy.cluster.vq import kmeans, vq, whiten
# Score of 20 students in on subjects
student_scores = [[80], [78], [55], [60], [62],
                [59], [48], [49], [51], [54],
                [72], [95], [78], [54], [50],
                [61], [57], [56], [65], [53]];
print(student_scores)

[[80], [78], [55], [60], [62], [59], [48], [49], [51], [54], [72], [95], [78], [54], [50], [61], [57], [56], [65], [53]]


Exercise 2) Next, normalize the raw data and calculate the centroids for
classifying two group of students:

In [14]:
student_scores = whiten(student_scores) # normalize a group of student
centroids,_ = kmeans(student_scores, 2) # devided into 2 groups of student

# print(student_scores)
print(centroids)

[[4.54233358]
 [6.58474976]]


Exercise 3) Finally, assign student into each group based on the nearest
distance:

In [15]:
result,_ = vq(student_scores, centroids)
print(result)

[1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]


Exercise 4) Modify the code in Exercise 1,2 and 3, in order to classify students
in to 4 groups and show the results.

In [16]:
centroidsFour,_ = kmeans(student_scores, 4)
print(centroidsFour)
resultFour,_ = vq(student_scores, centroidsFour)
print(resultFour)

[[4.95626326]
 [6.29064183]
 [7.76118148]
 [4.26638046]]
[1 1 3 0 0 0 3 3 3 3 1 2 1 3 3 0 0 3 0 3]


Exercise 5) Next, Try to classify the following scores of two subjects from 20
students into FOUR groups

In [17]:
student_scores = [[80 , 72] , [78 , 56] , [55 , 64] , [60 , 61] , [62 , 45] ,
[59 , 71] , [48 , 85] , [49 , 45] , [51 , 55] , [54 , 62] ,
[72 , 81] , [95 , 81] , [78 , 92] , [54 , 80] , [50 , 50] ,
[61 , 65] , [57 , 62] , [56 , 55] , [65 , 63] , [53 , 72]];

student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores, 4) # except only float/double
result,_ = vq(student_scores, centroids)

# # print(student_scores)
# print(centroids)
# print(result)

Exercise 6) Try the following code:

In [18]:
import scipy.constants

print("The PI is %16f"%(scipy.constants.pi))
print("The speed of light is c = %1.f"%(scipy.constants.c))
print("The newton's gravity constant is G = %1.f"%(scipy.constants.g))

The PI is         3.141593
The speed of light is c = 299792458
The newton's gravity constant is G = 10


In [19]:
scipy.constants.find("gram")

['atomic mass unit-kilogram relationship',
 'electron volt-kilogram relationship',
 'hartree-kilogram relationship',
 'hertz-kilogram relationship',
 'inverse meter-kilogram relationship',
 'joule-kilogram relationship',
 'kelvin-kilogram relationship',
 'kilogram-atomic mass unit relationship',
 'kilogram-electron volt relationship',
 'kilogram-hartree relationship',
 'kilogram-hertz relationship',
 'kilogram-inverse meter relationship',
 'kilogram-joule relationship',
 'kilogram-kelvin relationship']

In [20]:
print(scipy.constants.physical_constants["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


Exercise 9) Try to calculate the Energy(E) of your body (weight in kg) if
your entire body disappeared (Using E = mc2
equation).

In [21]:
print("E = mc^2")
m = 55
c = scipy.constants.c
e = m*(c**2)

print(f"E = {e} kg")

E = mc^2
E = 4.943153483052497e+18 kg


Exercise 10) Try the following command to find the min, max, mean and
variance of the data set (19, 18, 21, 16, 15, 17, 20, 18):

In [22]:
import scipy.stats
import numpy as np
x = np.array([19, 18, 21, 16, 15, 17, 20, 18])
print(scipy.stats.tmin(x), scipy.stats.tmax(x),
    scipy.stats.tmean(x), scipy.stats.tvar(x));

15 21 18.0 4.0


Exercise 11) Let’s add the following statement into the exercise 10 solution:


In [23]:
print(scipy.stats.describe(x))

DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


Exercise 12) Using student score of subject A as shown in Exercise 1, Try
the following code:


In [24]:
import scipy . stats
import numpy as np
student_scores = [[80] , [78] , [55] , [60] , [62] ,
[59] , [48] , [49] , [51] , [54] ,
[72] , [95] , [78] , [54] , [50] ,
[61] , [57] , [56] , [65] , [53]];
# print(scipy.stats.tmean(student_scores))
# print(scipy.stats.tstd(student_scores))
# print((62 - scipy.stats.tmean(student_scores)) / scipy.stats.tstd(student_scores))
# print(scipy.stats.zscore(student_scores))
# print(scipy.stats.mode(student_scores))
# print(scipy.stats.iqr(student_scores))

# Exercise 13) Calculate Z-score of all scores in Exercise 12 (Manually). Try
# to use package in scipy.stats to calculate. How is the result?
for i in student_scores:
    z_score = (i - scipy.stats.tmean(student_scores)) / scipy.stats.tstd(student_scores)
    print(f"Z-score of {i[0]}: {z_score}")

Z-score of 80: [1.44524896]
Z-score of 78: [1.28599288]
Z-score of 55: [-0.54545209]
Z-score of 60: [-0.14731188]
Z-score of 62: [0.01194421]
Z-score of 59: [-0.22693992]
Z-score of 48: [-1.10284838]
Z-score of 49: [-1.02322034]
Z-score of 51: [-0.86396425]
Z-score of 54: [-0.62508013]
Z-score of 72: [0.80822462]
Z-score of 95: [2.63966959]
Z-score of 78: [1.28599288]
Z-score of 54: [-0.62508013]
Z-score of 50: [-0.9435923]
Z-score of 61: [-0.06768384]
Z-score of 57: [-0.386196]
Z-score of 56: [-0.46582404]
Z-score of 65: [0.25082833]
Z-score of 53: [-0.70470817]
